#! /bin/bash

source ./.env

KEY_URL=https://api.github.com/user/keys

get() {
  curl -u $USERNAME:$TOKEN $1
}

delete() {
  curl -X "DELETE" -u $USERNAME:$TOKEN $1
}

map_ids() {
  jq -jr 'map(.id|tostring) | join("\n")'
}

keys_remaining() {
  get $KEY_URL | jq -r '.[0] != null'
}

delete_keys() {
  get $KEY_URL \
    | map_ids \
    | while read ID; do delete $KEY_URL/$ID; done
}

while [ `keys_remaining` = 'true' ]; do delete_keys; done
